### ISSUE TITLE
Немного с именованием не понял, если он Write, а от него наследуются Writer-ы, write же глагол? Поясни логику

### ISSUE THREAD

**Issue by boris-dev** [kalter704/liga-internship#5]
https://github.com/kalter704/liga-internship/blob/97d86d424333645be2d8b242c72d353658a01016/javacore-song-task/src/main/java/ru/liga/songtask/writes/BaseWrite.java#L5

**Comment by vasiliilantratov** [comment]
очередная опечатка, торопился 
исправил
