### ISSUE TITLE
Т.е. SongChange также умеет сохранять файлы? Не слишком ли много ответственности для одного класса?

### ISSUE THREAD

**Issue by boris-dev** [kalter704/liga-internship#8]
https://github.com/kalter704/liga-internship/blob/97d86d424333645be2d8b242c72d353658a01016/javacore-song-task/src/main/java/ru/liga/songtask/SongChange.java#L48

**Comment by vasiliilantratov** [comment]
Мне показалась это отличной идеей.
Вынесу из класса

**Comment by vasiliilantratov** [comment]
сделано
